### ISSUE TITLE
"Number Line: Distance" master checklist

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-distance#1]
# "Number Line: Distance" master checklist

## Design
- [x] **Sim folder and design doc created** (Date: 03/06/2020)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed** [suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (Date: //)
- [x] **Mockups complete** (Date: //)
  - [x] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: //)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] #69
  - [ ] #70
  - [ ] #71
- [ ] **Post-publication items**
  - [x] Share new features, design challenges, and treats with group!
  - [x] Email announcement
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //)

## Implementation
- [x] **Repository created** (Date: 3/5/2020)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 03/19/2020)
- [x] **Sim is "feature complete"** (Date: 06/25/2021)
- [x] **Code review completed** (Date: 07/20/2021)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)
- [x] **Published** (Date: //)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Dev testing started** (Date: 07/22/2021)
- [x] **Dev testing completed** (Date: 07/26/2021)
- [x] **First RC published** (Date: 07/31/2021)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 08/12/2021)

Viewport
Window
×
×
×

**Comment by amanda-phet** [comment]
Remaining items converted to issues. Closing!
